### ISSUE TITLE
Z-index issue with dropdown

### ISSUE THREAD

**Issue by jrichview** [israel-munoz/multiselect-dropdown#3]
We've used your library in a Power BI custom control which is hosted in a Power BI Report. The report is then hosted in an iframe on a website.  The standard browser's dropdown overlaps above the rest of the content. Your dropdown div does not (see attached examples).  I've tried setting a crazy high z-index but that seems to have no effect on the problem. 

Please let me know if you can suggest any sort of workaround for this.  You can see it firsthand here: https://floridahealthfinder-test.azurewebsites.net/QueryTool/QTResults.aspx?T=I

![multiselect-dropdown](https://user-images.githubusercontent.com/2236908/54439335-f5c5b580-470e-11e9-8c4d-767c73525c50.png)
![standard dropdown](https://user-images.githubusercontent.com/2236908/54439336-f65e4c00-470e-11e9-824a-710dfb11922c.PNG)

**Comment by israel-munoz** [comment]
I checked the page. The problem is that the <transform> container of the filters has z-index: 0, and the <transform> container of the grid has z-index: 1000. Also, the filters are inside an iframe. Any change in z-index for the options panel won't do any effect.
I've wanted to update the control to attach the options panel directly to the body, so it appears on top regardless of the rest of the page. But even so, you might still have problems with the iframe. You'd need to fix the z-index for the <transform> tags anyway.
I haven't got time to make that update, but I'll do it as soon as I can, and we'll see if that solves your issue.

**Comment by jrichview** [comment]
I noticed that the first <transform> tag has z-index of 0 and that setting it higher fixes the problem, but unfortunately a power bi custom visual has no practical means of controlling that. I've tried multiple ways.

**Comment by jrichview** [comment]
I also noticed that the problem is more pronounced in Edge browser than Chrome.

**Comment by jrichview** [comment]
I think I have a kludge workaround for now, but it's fragile. I think making the body the parent of that dropdown window would probably fix it.

**Comment by israel-munoz** [comment]
I made a new release for the component. As said before, I display the options at the <body> level, with z-index: 1000. If a bigger value is needed just set it for .multi-select-options-overlay in your stylesheet.
Please check if this one fixes the issue.

**Comment by jrichview** [comment]
Unfortunately, if I build the custom PBI visual with your current code, the dropdown stops working at all. Had to back out the changes.

**Comment by jrichview** [comment]
The powerBI report page is hosted within an iframe (different domain) so my website code cannot modify the content.  The custom control is hosted within an iframe internal to that content, but the z-index causing this whole problem is outside the control's iframe within that content. So my hands seem to be tied in terms of changing that z-index.

**Comment by jrichview** [comment]
I'm wondering how the system dropdown still works. Maybe it is a window with no parent?
